apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sonarqube
spec:
  storageClassName: sonarqube-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
