apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sonarqube-data
  resources:
    requests:
      storage: 10Gi
