apiVersion: apps/v1
kind: Deployment
metadata:
  name: tierlist-frontend-deployment
  namespace: tierlist-frotend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tierlist-frontend
  template:
    metadata:
      labels:
        app: tierlist-frontend
      annotations:
    spec:
      serviceAccountName: internal-app
      containers:
        - name: tierlist-frontend
          image: duk9741/tierlist-frontend:1
          ports:
            - containerPort: 80
