apiVersion: apps/v1
kind: Deployment
metadata:
  name: tierlist-api-deployment
  namespace: tierlist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tierlist-api
  template:
    metadata:
      labels:
        app: tierlist-api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-redis-config: 'internal/data/redis/config'
        vault.hashicorp.com/agent-inject-jwt-config: 'internal/data/jwt/config'
        vault.hashicorp.com/agent-inject-gmail-config: 'internal/data/gmail/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "internal/data/redis/config" -}}
            {{ range $k, $v := .Data }}
            export {{ $k }}={{ $v }}
            {{ end }}
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: tierlist-api
          image: duk9741/tierlist-api:22
          command:
            ['sh', '-c']
          args:
            ['source /vault/secrets/config']
          ports:
            - containerPort: 8080
