apiVersion: apps/v1
kind: Deployment
metadata:
  name: tierlist-api-deployment
  namespace: tierlist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tierlist-api
  template:
    metadata:
      labels:
        app: tierlist-api
      annotations:
    spec:
      serviceAccountName: internal-app
      containers:
        - name: tierlist-api
          image: duk9741/tierlist-api:68
          env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: tierlist-configmap
                key: redis_host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: tierlist-configmap
                key: redis_port
          - name: GMAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: tierlist-gmail-secret
                key: username
          - name: GMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tierlist-gmail-secret
                key: password
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: tierlist-jwt-secret
                key: secret
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: tierlist-localstack-secret
                key: localstack_access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: tierlist-localstack-secret
                key: localstack_secret_key
          - name: S3_REGION
            valueFrom:
              configMapKeyRef:
                name: tierlist-configmap
                key: s3_region
          - name: S3_ENDPOINT_URI
            valueFrom:
              configMapKeyRef:
                name: tierlist-configmap
                key: s3_endpoint_uri
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: tierlist-configmap
                key: s3_bucket
          ports:
            - containerPort: 8080
