apiVersion: apps/v1
kind: Deployment
metadata:
  name: tierlist-api-deployment
  namespace: tierlist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tierlist-api
  template:
    metadata:
      labels:
        app: tierlist-api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-redis-config: 'internal/data/redis/config'
        vault.hashicorp.com/agent-inject-jwt-config: 'internal/data/jwt/config'
        vault.hashicorp.com/agent-inject-gmail-config: 'internal/data/gmail/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "internal/data/redis/config" -}}
            export REDIS_HOST="{{ .Data.data.REDIS_HOST }}"
            export REDIS_PORT="{{ .Data.data.REDIS_PORT }}"
          {{- end }}
          {{- with secret "internal/data/jwt/config" -}}
            export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end }}
          {{- with secret "internal/data/gmail/config" -}}
            export GMAIL_USERNAME="{{ .Data.data.GMAIL_USERNAME }}"
            export GMAIL_PASSWORD="{{ .Data.data.GMAIL_PASSWORD }}"
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: tierlist-api
          image: duk9741/tierlist-api:22
          command:
            ['sh', '-c']
          args:
            ['source /vault/secrets/config && <entrypoint script>']
          ports:
            - containerPort: 8080
