apiVersion: apps/v1
kind: Deployment
metadata:
  name: tierlist-api-deployment
  namespace: tierlist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tierlist-api
  template:
    metadata:
      labels:
        app: tierlist-api
    spec:
      containers:
      - name: tierlist-api
        image: duk9741/tierlist-api:17
        ports:
        - containerPort: 8080