apiVersion: v1
kind: Service
metadata:
  name: tierlist-api-service
spec:
  selector:
    app: tierlist-api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32200
  type: NodePort
