apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: tierlist-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-data-pv
  resources:
    requests:
      storage: 20Gi

