apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tierlist-api
spec:
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      nodePort: 30010
  selector:
    app: mysql
  type: NodePort